---
abstract: 'Text::Caml for Dancer'
author:
  - 'Viacheslav Tykhanovskyi <vti@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Template-Caml
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Dancer: 1.3072
  Text::Caml: 0.009004
  perl: 5.8.7
resources:
  bugtracker: http://github.com/vti/dancer-template-caml/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/vti/dancer-template-caml/
version: 0.009001
